SHOW TABLES;



SET FOREIGN_KEY_CHECKS = false;
DROP TABLE IF EXISTS `main`;
DROP TABLE IF EXISTS `media`;
DROP TABLE IF EXISTS `space_db`;
DROP TABLE IF EXISTS `fact_tags`;
DROP TABLE IF EXISTS `cat_db`;


SET FOREIGN_KEY_CHECKS = true;